# playstore-country-check 0.3 by treysis / https://github.com/treysis
# License: LGPL 2.1
#
# Checks the availability of apps in local variants of Google's PlayStore.
#
# Runs on Python 3.8. Relies on 'requests' and 'BeautifulSoup4'
# install with:
#     pip install requests
#     pip install beautifulsoup4
#

try:
    import requests
except ImportError as error:
    print("Error: error while loading 'requests'! Install with 'pip install requests' and try again.")
    exit()

try:
    from bs4 import BeautifulSoup
except ImportError as error:
    print("Error: error while loading 'BeautifulSoup4'! Install with 'pip install beautifulsoup4' and try again.")
    exit()

from sys import stdout
from sys import argv
from multiprocessing.dummy import Pool
from itertools import product



# Initialize country codes and names
#"""
GL_COUNTRY_CODES = {
    "ad": "Andorra",
    "ae": "United Arab Emirates",
    "af": "Afghanistan",
    "ag": "Antigua and Barbuda",
    "ai": "Anguilla",
    "al": "Albania",
    "am": "Armenia",
    "an": "Netherlands Antilles",
    "ao": "Angola",
    "aq": "Antarctica",
    "ar": "Argentina",
    "as": "American Samoa",
    "at": "Austria",
    "au": "Australia",
    "aw": "Aruba",
    "az": "Azerbaijan",
    "ba": "Bosnia and Herzegovina",
    "bb": "Barbados",
    "bd": "Bangladesh",
    "be": "Belgium",
    "bf": "Burkina Faso",
    "bg": "Bulgaria",
    "bh": "Bahrain",
    "bi": "Burundi",
    "bj": "Benin",
    "bm": "Bermuda",
    "bn": "Brunei",
    "bo": "Bolivia",
    "br": "Brazil",
    "bs": "Bahamas",
    "bt": "Bhutan",
    "bv": "Bouvet Island",
    "bw": "Botswana",
    "by": "Belarus",
    "bz": "Belize",
    "ca": "Canada",
    "cc": "Cocos (Keeling) Islands",
    "cd": "Congo (DRC)",
    "cf": "Central African Republic",
    "cg": "Congo (Republic)",
    "ch": "Switzerland",
    "ci": "Ivory Coast (Côte d'Ivoire)",
    "ck": "Cook Islands",
    "cl": "Chile",
    "cm": "Cameroon",
    "cn": "China",
    "co": "Colombia",
    "cr": "Costa Rica",
    "cu": "Cuba",
    "cv": "Cape Verde",
    "cx": "Christmas Island",
    "cy": "Cyprus",
    "cz": "Czech Republic",
    "de": "Germany",
    "dj": "Djibouti",
    "dk": "Denmark",
    "dm": "Dominica",
    "do": "Dominican Republic",
    "dz": "Algeria",
    "ec": "Ecuador",
    "ee": "Estonia",
    "eg": "Egypt",
    "eh": "Western Sahara",
    "er": "Eritrea",
    "es": "Spain",
    "et": "Ethiopia",
    "fi": "Finland",
    "fj": "Fiji",
    "fk": "Falkland Islands (Islas Malvinas)",
    "fm": "Micronesia",
    "fo": "Faroe Islands",
    "fr": "France",
    "ga": "Gabon",
    "gb": "United Kingdom",
    "gd": "Grenada",
    "ge": "Georgia",
    "gf": "French Guiana",
    "gg": "Guernsey",
    "gh": "Ghana",
    "gi": "Gibraltar",
    "gl": "Greenland",
    "gm": "The Gambia",
    "gn": "Guinea",
    "gp": "Guadeloupe",
    "gq": "Equatorial Guinea",
    "gr": "Greece",
    "gs": "South Georgia and the South Sandwich Islands",
    "gt": "Guatemala",
    "gu": "Guam",
    "gw": "Guinea-Bissau",
    "gy": "Guyana",
    "hk": "Hong Kong",
    "hm": "Heard Island and McDonald Islands",
    "hn": "Honduras",
    "hr": "Croatia",
    "ht": "Haiti",
    "hu": "Hungary",
    "id": "Indonesia",
    "ie": "Ireland",
    "il": "Israel",
    "im": "Isle of Man",
    "in": "India",
    "io": "British Indian Ocean Territory",
    "iq": "Iraq",
    "ir": "Iran",
    "is": "Iceland",
    "it": "Italy",
    "je": "Jersey",
    "jm": "Jamaica",
    "jo": "Jordan",
    "jp": "Japan",
    "ke": "Kenya",
    "kg": "Kyrgyzstan",
    "kh": "Cambodia",
    "ki": "Kiribati",
    "km": "Comoros",
    "kn": "Saint Kitts and Nevis",
    "kr": "South Korea",
    "kw": "Kuwait",
    "ky": "Cayman Islands",
    "kz": "Kazakhstan",
    "la": "Laos",
    "lb": "Lebanon",
    "lc": "Saint Lucia",
    "li": "Liechtenstein",
    "lk": "Sri Lanka",
    "lr": "Liberia",
    "ls": "Lesotho",
    "lt": "Lithuania",
    "lu": "Luxembourg",
    "lv": "Latvia",
    "ly": "Libya",
    "ma": "Morocco",
    "mc": "Monaco",
    "md": "Moldova",
    "me": "Montenegro",
    "mg": "Madagascar",
    "mh": "Marshall Islands",
    "mk": "North Macedonia",
    "ml": "Mali",
    "mm": "Myanmar (Burma)",
    "mn": "Mongolia",
    "mo": "Macau",
    "mp": "Northern Mariana Islands",
    "mq": "Martinique",
    "mr": "Mauritania",
    "ms": "Montserrat",
    "mt": "Malta",
    "mu": "Mauritius",
    "mv": "Maldives",
    "mw": "Malawi",
    "mx": "Mexico",
    "my": "Malaysia",
    "mz": "Mozambique",
    "na": "Namibia",
    "nc": "New Caledonia",
    "ne": "Niger",
    "nf": "Norfolk Island",
    "ng": "Nigeria",
    "ni": "Nicaragua",
    "nl": "Netherlands",
    "no": "Norway",
    "np": "Nepal",
    "nr": "Nauru",
    "nu": "Niue",
    "nz": "New Zealand",
    "om": "Oman",
    "pa": "Panama",
    "pe": "Peru",
    "pf": "French Polynesia",
    "pg": "Papua New Guinea",
    "ph": "Philippines",
    "pk": "Pakistan",
    "pl": "Poland",
    "pm": "Saint Pierre and Miquelon",
    "pn": "Pitcairn Islands",
    "pr": "Puerto Rico",
    "ps": "Palestinian Territories",
    "pt": "Portugal",
    "pw": "Palau",
    "py": "Paraguay",
    "qa": "Qatar",
    "re": "Réunion",
    "ro": "Romania",
    "rs": "Serbia",
    "ru": "Russia",
    "rw": "Rwanda",
    "sa": "Saudi Arabia",
    "sb": "Solomon Islands",
    "sc": "Seychelles",
    "sd": "Sudan",
    "se": "Sweden",
    "sg": "Singapore",
    "sh": "Saint Helena",
    "si": "Slovenia",
    "sj": "Svalbard and Jan Mayen",
    "sk": "Slovakia",
    "sl": "Sierra Leone",
    "sm": "San Marino",
    "sn": "Senegal",
    "so": "Somalia",
    "sr": "Suriname",
    "ss": "South Sudan",
    "st": "São Tomé and Príncipe",
    "sv": "El Salvador",
    "sz": "Eswatini (Swaziland)",
    "tc": "Turks and Caicos Islands",
    "td": "Chad",
    "tf": "French Southern Territories",
    "tg": "Togo",
    "th": "Thailand",
    "tj": "Tajikistan",
    "tk": "Tokelau",
    "tl": "Timor-Leste",
    "tm": "Turkmenistan",
    "tn": "Tunisia",
    "to": "Tonga",
    "tr": "Turkey",
    "tt": "Trinidad and Tobago",
    "tv": "Tuvalu",
    "tw": "Taiwan",
    "tz": "Tanzania",
    "ua": "Ukraine",
    "ug": "Uganda",
    "um": "U.S. Minor Outlying Islands",
    "us": "United States",
    "uy": "Uruguay",
    "uz": "Uzbekistan",
    "va": "Vatican City",
    "vc": "Saint Vincent and the Grenadines",
    "ve": "Venezuela",
    "vg": "British Virgin Islands",
    "vi": "U.S. Virgin Islands",
    "vn": "Vietnam",
    "vu": "Vanuatu",
    "wf": "Wallis and Futuna",
    "ws": "Samoa",
    "xk": "Kosovo",
    "ye": "Yemen",
    "yt": "Mayotte",
    "za": "South Africa",
    "zm": "Zambia",
    "zw": "Zimbabwe",
}

#"""

# Mildly shortened list
"""
GL_COUNTRY_CODES = {
    "ad": "Andorra",
    "ae": "United Arab Emirates",
    "af": "Afghanistan",
    "al": "Albania",
    "am": "Armenia",
    "ao": "Angola",
    "ar": "Argentina",
    "at": "Austria",
    "au": "Australia",
    "az": "Azerbaijan",
    "ba": "Bosnia and Herzegovina",
    "bd": "Bangladesh",
    "be": "Belgium",
    "bf": "Burkina Faso",
    "bg": "Bulgaria",
    "bh": "Bahrain",
    "bi": "Burundi",
    "br": "Brazil",
    "bw": "Botswana",
    "by": "Belarus",
    "ca": "Canada",
    "cd": "Congo (DRC)",
    "cf": "Central African Republic",
    "cg": "Congo (Republic)",
    "ch": "Switzerland",
    "ci": "Ivory Coast (Côte d'Ivoire)",
    "cl": "Chile",
    "cm": "Cameroon",
    "cn": "China",
    "co": "Colombia",
    "cr": "Costa Rica",
    "cu": "Cuba",
    "cy": "Cyprus",
    "cz": "Czech Republic",
    "de": "Germany",
    "dk": "Denmark",
    "do": "Dominican Republic",
    "dz": "Algeria",
    "ec": "Ecuador",
    "ee": "Estonia",
    "eg": "Egypt",
    "er": "Eritrea",
    "es": "Spain",
    "fi": "Finland",
    "fo": "Faroe Islands",
    "fr": "France",
    "gb": "United Kingdom",
    "ge": "Georgia",
    "gg": "Guernsey",
    "gh": "Ghana",
    "gi": "Gibraltar",
    "gl": "Greenland",
    "gn": "Guinea",
    "gr": "Greece",
    "hk": "Hong Kong",
    "hn": "Honduras",
    "hr": "Croatia",
    "hu": "Hungary",
    "id": "Indonesia",
    "ie": "Ireland",
    "il": "Israel",
    "im": "Isle of Man",
    "in": "India",
    "iq": "Iraq",
    "ir": "Iran",
    "is": "Iceland",
    "it": "Italy",
    "je": "Jersey",
    "jm": "Jamaica",
    "jo": "Jordan",
    "jp": "Japan",
    "ke": "Kenya",
    "kg": "Kyrgyzstan",
    "kh": "Cambodia",
    "kr": "South Korea",
    "kw": "Kuwait",
    "kz": "Kazakhstan",
    "lb": "Lebanon",
    "li": "Liechtenstein",
    "lk": "Sri Lanka",
    "lr": "Liberia",
    "lt": "Lithuania",
    "lu": "Luxembourg",
    "lv": "Latvia",
    "ly": "Libya",
    "ma": "Morocco",
    "mc": "Monaco",
    "md": "Moldova",
    "me": "Montenegro",
    "mg": "Madagascar",
    "mk": "North Macedonia",
    "ml": "Mali",
    "mn": "Mongolia",
    "mr": "Mauritania",
    "mt": "Malta",
    "mu": "Mauritius",
    "mx": "Mexico",
    "my": "Malaysia",
    "mz": "Mozambique",
    "na": "Namibia",
    "ne": "Niger",
    "ng": "Nigeria",
    "nl": "Netherlands",
    "no": "Norway",
    "np": "Nepal",
    "nz": "New Zealand",
    "om": "Oman",
    "pa": "Panama",
    "pe": "Peru",
    "ph": "Philippines",
    "pk": "Pakistan",
    "pl": "Poland",
    "pr": "Puerto Rico",
    "pt": "Portugal",
    "py": "Paraguay",
    "qa": "Qatar",
    "ro": "Romania",
    "rs": "Serbia",
    "ru": "Russia",
    "sa": "Saudi Arabia",
    "sd": "Sudan",
    "se": "Sweden",
    "sg": "Singapore",
    "si": "Slovenia",
    "sk": "Slovakia",
    "sm": "San Marino",
    "sn": "Senegal",
    "td": "Chad",
    "tg": "Togo",
    "th": "Thailand",
    "tj": "Tajikistan",
    "tm": "Turkmenistan",
    "tn": "Tunisia",
    "tr": "Turkey",
    "tw": "Taiwan",
    "tz": "Tanzania",
    "ua": "Ukraine",
    "us": "United States",
    "uy": "Uruguay",
    "uz": "Uzbekistan",
    "va": "Vatican City",
    "ve": "Venezuela",
    "vn": "Vietnam",
    "xk": "Kosovo",
    "za": "South Africa",
}
"""

# Strongly shortened list, focus on Europe
"""
GL_COUNTRY_CODES = {
    "ad": "Andorra",
    "ae": "United Arab Emirates",
    "af": "Afghanistan",
    "al": "Albania",
    "am": "Armenia",
    "ao": "Angola",
    "ar": "Argentina",
    "at": "Austria",
    "au": "Australia",
    "az": "Azerbaijan",
    "ba": "Bosnia and Herzegovina",
    "bd": "Bangladesh",
    "be": "Belgium",
    "bg": "Bulgaria",
    "br": "Brazil",
    "by": "Belarus",
    "ca": "Canada",
    "cd": "Congo (DRC)",
    "cg": "Congo (Republic)",
    "ch": "Switzerland",
    "cl": "Chile",
    "cm": "Cameroon",
    "cn": "China",
    "co": "Colombia",
    "cu": "Cuba",
    "cy": "Cyprus",
    "cz": "Czech Republic",
    "de": "Germany",
    "dk": "Denmark",
    "do": "Dominican Republic",
    "dz": "Algeria",
    "ee": "Estonia",
    "eg": "Egypt",
    "er": "Eritrea",
    "es": "Spain",
    "fi": "Finland",
    "fo": "Faroe Islands",
    "fr": "France",
    "gb": "United Kingdom",
    "ge": "Georgia",
    "gg": "Guernsey",
    "gh": "Ghana",
    "gi": "Gibraltar",
    "gl": "Greenland",
    "gr": "Greece",
    "hk": "Hong Kong",
    "hn": "Honduras",
    "hr": "Croatia",
    "hu": "Hungary",
    "id": "Indonesia",
    "ie": "Ireland",
    "il": "Israel",
    "im": "Isle of Man",
    "in": "India",
    "iq": "Iraq",
    "ir": "Iran",
    "is": "Iceland",
    "it": "Italy",
    "je": "Jersey",
    "jo": "Jordan",
    "jp": "Japan",
    "ke": "Kenya",
    "kr": "South Korea",
    "kz": "Kazakhstan",
    "lb": "Lebanon",
    "li": "Liechtenstein",
    "lk": "Sri Lanka",
    "lt": "Lithuania",
    "lu": "Luxembourg",
    "lv": "Latvia",
    "ly": "Libya",
    "ma": "Morocco",
    "mc": "Monaco",
    "md": "Moldova",
    "me": "Montenegro",
    "mk": "North Macedonia",
    "mn": "Mongolia",
    "mt": "Malta",
    "mu": "Mauritius",
    "mx": "Mexico",
    "mz": "Mozambique",
    "na": "Namibia",
    "ng": "Nigeria",
    "nl": "Netherlands",
    "no": "Norway",
    "np": "Nepal",
    "nz": "New Zealand",
    "om": "Oman",
    "pe": "Peru",
    "ph": "Philippines",
    "pk": "Pakistan",
    "pl": "Poland",
    "pr": "Puerto Rico",
    "pt": "Portugal",
    "py": "Paraguay",
    "qa": "Qatar",
    "ro": "Romania",
    "rs": "Serbia",
    "ru": "Russia",
    "sa": "Saudi Arabia",
    "sd": "Sudan",
    "se": "Sweden",
    "sg": "Singapore",
    "si": "Slovenia",
    "sk": "Slovakia",
    "sm": "San Marino",
    "tg": "Togo",
    "th": "Thailand",
    "tn": "Tunisia",
    "tr": "Turkey",
    "tw": "Taiwan",
    "tz": "Tanzania",
    "ua": "Ukraine",
    "us": "United States",
    "uy": "Uruguay",
    "uz": "Uzbekistan",
    "va": "Vatican City",
    "ve": "Venezuela",
    "vn": "Vietnam",
    "xk": "Kosovo",
    "za": "South Africa",
}
"""

# Some bigger countries only, focus on Europe
"""
GL_COUNTRY_CODES = {
    "ad": "Andorra",
    "ae": "United Arab Emirates",
    "al": "Albania",
    "am": "Armenia",
    "ar": "Argentina",
    "at": "Austria",
    "au": "Australia",
    "ba": "Bosnia and Herzegovina",
    "bd": "Bangladesh",
    "be": "Belgium",
    "bg": "Bulgaria",
    "br": "Brazil",
    "by": "Belarus",
    "ca": "Canada",
    "ch": "Switzerland",
    "cm": "Cameroon",
    "cn": "China",
    "co": "Colombia",
    "cu": "Cuba",
    "cy": "Cyprus",
    "cz": "Czech Republic",
    "de": "Germany",
    "dk": "Denmark",
    "do": "Dominican Republic",
    "dz": "Algeria",
    "ee": "Estonia",
    "eg": "Egypt",
    "er": "Eritrea",
    "es": "Spain",
    "fi": "Finland",
    "fo": "Faroe Islands",
    "fr": "France",
    "gb": "United Kingdom",
    "ge": "Georgia",
    "gg": "Guernsey",
    "gh": "Ghana",
    "gi": "Gibraltar",
    "gl": "Greenland",
    "gr": "Greece",
    "hk": "Hong Kong",
    "hr": "Croatia",
    "hu": "Hungary",
    "id": "Indonesia",
    "ie": "Ireland",
    "il": "Israel",
    "im": "Isle of Man",
    "in": "India",
    "iq": "Iraq",
    "ir": "Iran",
    "is": "Iceland",
    "it": "Italy",
    "je": "Jersey",
    "jp": "Japan",
    "ke": "Kenya",
    "kr": "South Korea",
    "kz": "Kazakhstan",
    "lb": "Lebanon",
    "li": "Liechtenstein",
    "lk": "Sri Lanka",
    "lt": "Lithuania",
    "lu": "Luxembourg",
    "lv": "Latvia",
    "ly": "Libya",
    "ma": "Morocco",
    "mc": "Monaco",
    "md": "Moldova",
    "me": "Montenegro",
    "mk": "North Macedonia",
    "mt": "Malta",
    "mx": "Mexico",
    "na": "Namibia",
    "ng": "Nigeria",
    "nl": "Netherlands",
    "no": "Norway",
    "nz": "New Zealand",
    "ph": "Philippines",
    "pk": "Pakistan",
    "pl": "Poland",
    "pr": "Puerto Rico",
    "pt": "Portugal",
    "py": "Paraguay",
    "qa": "Qatar",
    "ro": "Romania",
    "rs": "Serbia",
    "ru": "Russia",
    "sa": "Saudi Arabia",
    "se": "Sweden",
    "sg": "Singapore",
    "si": "Slovenia",
    "sk": "Slovakia",
    "sm": "San Marino",
    "th": "Thailand",
    "tr": "Turkey",
    "tw": "Taiwan",
    "ua": "Ukraine",
    "us": "United States",
    "uy": "Uruguay",
    "va": "Vatican City",
    "ve": "Venezuela",
    "xk": "Kosovo",
    "za": "South Africa",
}
"""


# Europe only
#"""
GL_COUNTRY_CODES = {
    "ad": "Andorra",
    "al": "Albania",
    "at": "Austria",
    "ba": "Bosnia and Herzegovina",
    "be": "Belgium",
    "bg": "Bulgaria",
    "by": "Belarus",
    "ch": "Switzerland",
    "cn": "China",
    "cy": "Cyprus",
    "cz": "Czech Republic",
    "de": "Germany",
    "dk": "Denmark",
    "ee": "Estonia",
    "es": "Spain",
    "fi": "Finland",
    "fo": "Faroe Islands",
    "fr": "France",
    "gb": "United Kingdom",
    "gg": "Guernsey",
    "gi": "Gibraltar",
    "gl": "Greenland",
    "gr": "Greece",
    "hr": "Croatia",
    "hu": "Hungary",
    "ie": "Ireland",
    "il": "Israel",
    "im": "Isle of Man",
    "is": "Iceland",
    "it": "Italy",
    "je": "Jersey",
    "li": "Liechtenstein",
    "lt": "Lithuania",
    "lu": "Luxembourg",
    "lv": "Latvia",
    "mc": "Monaco",
    "md": "Moldova",
    "me": "Montenegro",
    "mk": "North Macedonia",
    "mt": "Malta",
    "nl": "Netherlands",
    "no": "Norway",
    "pl": "Poland",
    "pt": "Portugal",
    "ro": "Romania",
    "rs": "Serbia",
    "ru": "Russia",
    "se": "Sweden",
    "si": "Slovenia",
    "sk": "Slovakia",
    "sm": "San Marino",
    "tr": "Turkey",
    "ua": "Ukraine",
    "va": "Vatican City",
    "xk": "Kosovo",
}
#"""

# Short country list for faster testing
"""
GL_COUNTRY_CODES = {
    "ad": "Andorra",
    "at": "Austria",
    "ch": "Switzerland",
    "gb": "United Kingdom",
    "us": "United States",
    "zw": "Zimbabwe",
}
"""

print("--\nplaystore-country-check 0.3:\nChecking the enabled PlayStore countries for a specified", \
        "app\n(e.g. use package name: de.rki.coronawarnapp).")
print("Sourcecode @ https://github.com/treysis/playstore-country-check\n")
print("Usage: python playstore_country_check.py <playstore.package.name>\n\n")

# Initialize variables.
cwaa = list()
cwana = list()
nCountries = 1
delete = "\b" * 35
psurl = "https://play.google.com/store/apps/details?id="

def check(appname, gl):
    # Prevent some potential buffer overflow
    if (len(cwaa) + len(cwana)) >= nCountries:
        cwaa.clear()
        cwana.clear()

    # Progress indicator
    print("{0}{0}{1:{2}}".format(delete, len(cwaa)+len(cwana), 3),
          end=" of " + str(nCountries) + "... (current: " + gl + ", total available: " + str(len(cwaa)) + ")")
    stdout.flush()
    # Search PlayStore webpage for install button (no matter if free/buy).
    # This is done by searching all <button> tags, and install button has
    # class = ['LkLjZd', 'ScJHi', 'HPiPcc', 'IfEcue'] (arbitrary array by
    # Google? Should be auto-detected in a future release by querying a
    # known-good app and extract the string from there).
    url = psurl + appname + "&gl=" + gl
    soup = BeautifulSoup(requests.get(url).text, 'lxml')
    if soup.find_all(lambda tag: tag.name == 'button' and tag.get('class') == ['LkLjZd', 'ScJHi', 'HPiPcc', 'IfEcue']):
        # Circumvent error when country code is not in the loaded country list when invoked as module
        try:
            cwaa.append(GL_COUNTRY_CODES[gl])
        except:
            cwaa.append('UNKNOWN')
        print("{0}{0}{1:{2}}".format(delete, len(cwaa) + len(cwana), 3),
              end=" of " + str(nCountries) + "... (current: " + gl + ", total available: " + str(len(cwaa)) + ")")
        stdout.flush()
        return True
    else:
        try:
            cwana.append(GL_COUNTRY_CODES[gl])
        except:
            cwana.append('UNKNOWN')
        print("{0}{0}{1:{2}}".format(delete, len(cwaa) + len(cwana), 3),
              end=" of " + str(nCountries) + "... (current: " + gl + ", total available: " + str(len(cwaa)) + ")")
        stdout.flush()
        return False


def availability(appname, threads=10):

    cwaa.clear()
    cwana.clear()
    global nCountries
    nCountries = len(GL_COUNTRY_CODES)

    # Start checking localized PlayStores
    print("Checking " + str(nCountries) + " countries for \'" + appname + "\' with " + str(threads) + " simultaneous threads:")

    # Default number of threads is 10, which should not hit Google's rate limit
    pool = Pool(threads)
    pool.starmap(check, product([appname], list(GL_COUNTRY_CODES.keys())))
    pool.close()
    pool.join()

    # Reset
    nCountries = 1

    # Some ugly output formatting...
    print(delete + "(total available: " + str(len(cwaa)) + ") ...done!                   \n")

    # Prepare and format output
    cwaa.sort()
    cwana.sort()
    print("App available in " + str(len(cwaa)) + " tested local PlayStores:")
    print(*cwaa, sep=", ", end=".\n")
    print("\nNot available in:")
    print(*cwana, sep=", ", end=".\n")
    print("\n--- Finished, exiting... ---")

    # Return list of countries for which app is available
    return cwaa


# This is where it starts!
if __name__ == '__main__':
    # Check for app name from cmdline
    if len(argv)<2:
        appname = 'de.rki.coronawarnapp'
        print("No app name specified. Defaulting to \'" + appname + "\'\n")
    else:
        appname = argv[1]

    availability(appname)
